[package]
name = "render-game"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { path = "../../../lib/config" }
api = { path = "../../../lib/api" }

api-render-game = { path = "../../../game/api-render-game" }
client-render-game = { path = "../../../game/client-render-game" }

[lib]
crate-type = ["cdylib"]
