[package]
name = "skin-convert"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
assets-splitting = { path = "../../game/assets-splitting" }
image-utils = { path = "../../lib/image-utils" }
