[package]
name = "prediction_timer_ui"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
api-ui = { path = "../../../lib/api-ui" }
math = { path = "../../../lib/math" }
ui-base = { path = "../../../lib/ui-base" }
ui-generic = { path = "../../../lib/ui-generic" }

api-ui-game = { path = "../../../game/api-ui-game" }
prediction-timer = { path = "../../../game/prediction-timer" }

egui = { version = "0.32.2", default-features = false, features = ["serde"] }
egui_plot = { version = "0.33.0" }
