[package]
name = "http-accounts"
version = "0.1.0"
edition = "2024"

[dependencies]
base-io-traits = { path = "../../lib/base-io-traits" }

anyhow = { version = "1.0.99", features = ["backtrace"] }
async-trait = "0.1.89"
url = { version = "2.5.7", features = ["serde"] }

ddnet-account-client = { version = "0.2.0" }
ddnet-account-client-http-fs = { version = "0.3.0" }
