[package]
name = "legacy-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
base = { path = "../../lib/base" }
base-http = { path = "../../lib/base-http" }
base-io = { path = "../../lib/base-io" }
bin-patch = { path = "../../lib/bin-patch" }
math = { path = "../../lib/math" }
network = { path = "../../lib/network" }
pool = { path = "../../lib/pool" }

game-base = { path = "../game-base" }
game-interface = { path = "../game-interface" }
game-network = { path = "../game-network" }
game-server = { path = "../game-server" }
legacy-map = { path = "../legacy-map" }
map = { path = "../map" }
vanilla = { path = "../vanilla" }

libtw2-gamenet-ddnet = { git = "https://github.com/Jupeyy/libtw2.git", rev = "0e6a9e2f21f12bf34efd2da9f41043e1e3de4c57" }
libtw2-net = { git = "https://github.com/Jupeyy/libtw2.git", rev = "0e6a9e2f21f12bf34efd2da9f41043e1e3de4c57" }
libtw2-packer = { git = "https://github.com/Jupeyy/libtw2.git", rev = "0e6a9e2f21f12bf34efd2da9f41043e1e3de4c57" }
libtw2-snapshot = { git = "https://github.com/Jupeyy/libtw2.git", rev = "0e6a9e2f21f12bf34efd2da9f41043e1e3de4c57" }

anyhow = { version = "1.0.99", features = ["backtrace"] }
# stuck for compat with libtw2
arrayvec = "=0.5.2"
bincode = { version = "2.0.1", features = ["serde"] }
hexdump = "0.1.2"
rand = { version = "0.9.2", features = ["thread_rng"] }
sha2 = "0.10.9"

futures = "0.3.31"
hex = "0.4.3"
log = "0.4.28"
rayon = "1.11.0"
tokio = { version = "1.47.1", features = [
  "rt-multi-thread",
  "sync",
  "fs",
  "time",
  "macros",
] }
warn = "0.2.2"
